---
# tasks file for r1soft
- name: Copy repo to RedHAt Family
  when: ansible_os_family == "RedHat"
  template: 
    src: ../templates/r1soft.repo
    dest: /etc/yum.repos.d/r1soft.repo




- name: Create repo for Ubuntu
  when: ansible_os_family == "Debian"
  shell: "{{ item }}"
  with_items: 
    - "echo deb http://repo.r1soft.com/apt stable main >> /etc/apt/sources.list"
    - "wget http://repo.r1soft.com/r1soft.asc"
    - "apt-key add r1soft.asc"
    - "apt-get update "



- name: Install r1soft agent
  package: 
    name: serverbackup-enterprise-agent


- name: Run r1soft agent
  when: ( ansible_os_family == "RedHat"  and ansible_distribution_version ==  "6" )
  service:
    name: cdp-agent
    state: started


- name: Run r1soft agent
  when: 
    - ( ansible_os_family == "RedHat"  and ansible_distribution_version ==  "7" )
    - ( ansible_os_family == "Debian" ) 
  systemd:
    name: sbm-agent
    state: started



- name: Get Key
  when: ansible_os_family == "RedHat"
  command: r1soft-setup --get-key "{{ r1softserver }}"

